import { Barlow } from 'next/font/google';
import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import '../styles/globals.scss';
import Footer from '@/components/Footer';

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'PrevSeg',
  description: 'Generated by create next app',
  openGraph: {
    siteName: 'PrevSeg',
    title: 'PrevSeg',
    description: 'Curso de formação, extensão e reciclagem de vigilantes',
    url: 'http://academiamontecastelo.com.br/',
    images: [
      {
        url: 'http://academiamontecastelo.com.br/icon512x512.png',
        width: 1280,
        height: 720,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PrevSeg',
    description: 'Curso de formação, extensão e reciclagem de vigilantes',
    images: ['http://academiamontecastelo.com.br/icon512x512.png'],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" className={barlow.className}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>

      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
