import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import '../styles/globals.scss';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Academia Monte Castelo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
